// Bundle the embedded brand assets (coin + fonts) into an ES module the browser
// generator can import, and copy the shared template alongside it.
// Run: node scripts/build-webapp.mjs
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pub = join(root, 'webapp', 'public');
mkdirSync(pub, { recursive: true });

const coinB64 = readFileSync(join(root, 'assets/coin.b64'), 'utf8').trim();
const fontFace = (family, weight, file) => {
  const b64 = readFileSync(join(root, 'assets/fonts', file)).toString('base64');
  return `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};font-display:swap;src:url(data:font/ttf;base64,${b64}) format('truetype')}`;
};
const fontCss = [
  fontFace('Grenze Gotisch', 700, 'grenze700.ttf'),
  fontFace('Hanken Grotesk', 400, 'hanken400.ttf'),
  fontFace('Hanken Grotesk', 700, 'hanken700.ttf'),
].join('\n');

writeFileSync(
  join(pub, 'assets.js'),
  `// AUTO-GENERATED by scripts/build-webapp.mjs — do not edit by hand.\n` +
    `export const coinUri = ${JSON.stringify(`data:image/png;base64,${coinB64}`)};\n` +
    `export const fontCss = ${JSON.stringify(fontCss)};\n`,
);
copyFileSync(join(root, 'src/reportCardTemplate.js'), join(pub, 'reportCardTemplate.js'));
console.log('webapp assets built ->', pub);
